"""Add GTU admin model

Revision ID: 747ac2c69333
Revises: 561631c3b5c0
Create Date: 2024-12-28 01:25:52.066687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747ac2c69333'
down_revision: Union[str, None] = '561631c3b5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtu_admin_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtu_admin_details_id'), 'gtu_admin_details', ['id'], unique=False)
    op.drop_index('ix_courses_code', table_name='courses')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_index('ix_courses_name', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_faculty_course_assignments_id', table_name='faculty_course_assignments')
    op.drop_table('faculty_course_assignments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_course_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('academic_year', sa.VARCHAR(), nullable=True),
    sa.Column('semester', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_faculty_course_assignments_id', 'faculty_course_assignments', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('credits', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=9), nullable=True),
    sa.Column('semester', sa.INTEGER(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_name', 'courses', ['name'], unique=False)
    op.create_index('ix_courses_id', 'courses', ['id'], unique=False)
    op.create_index('ix_courses_code', 'courses', ['code'], unique=1)
    op.drop_index(op.f('ix_gtu_admin_details_id'), table_name='gtu_admin_details')
    op.drop_table('gtu_admin_details')
    # ### end Alembic commands ###
